/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Admin
 */
public class Form_AD extends javax.swing.JFrame {

    /**
     * Creates new form Form_AD
     */
    public Form_AD() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnQLHS = new javax.swing.JButton();
        btnQLGV = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JButton();
        btnDoimatkhau = new javax.swing.JButton();
        btnQLTKB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORM_AD");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        btnQLHS.setBackground(new java.awt.Color(0, 153, 0));
        btnQLHS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQLHS.setForeground(new java.awt.Color(255, 255, 255));
        btnQLHS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconstu.png"))); // NOI18N
        btnQLHS.setText("QUẢN LÝ HỌC SINH");
        btnQLHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHSActionPerformed(evt);
            }
        });

        btnQLGV.setBackground(new java.awt.Color(0, 153, 0));
        btnQLGV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQLGV.setForeground(new java.awt.Color(255, 255, 255));
        btnQLGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icontea.png"))); // NOI18N
        btnQLGV.setText("QUẢN LÝ GIÁO VIÊN");
        btnQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGVActionPerformed(evt);
            }
        });

        btnQLTK.setBackground(new java.awt.Color(0, 153, 0));
        btnQLTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQLTK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconuser.png"))); // NOI18N
        btnQLTK.setText("QUẢN LÝ TÀI KHOẢN");
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 198));
        jLabel1.setText("XIN CHÀO ADMIN");

        jLabel3.setText("jLabel3");

        btnDangxuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconlogout.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        btnDoimatkhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconkey.png"))); // NOI18N
        btnDoimatkhau.setText("Đổi mật khẩu");
        btnDoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoimatkhauActionPerformed(evt);
            }
        });

        btnQLTKB.setBackground(new java.awt.Color(0, 153, 0));
        btnQLTKB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQLTKB.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTKB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_tkb.png"))); // NOI18N
        btnQLTKB.setText("QUẢN LÝ THỜI KHÓA BIỂU");
        btnQLTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(296)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        			.addContainerGap(59, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(99, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnQLGV, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(btnDoimatkhau)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnDangxuat))
        				.addComponent(btnQLTKB, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnQLTK, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnQLHS, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE))
        			.addGap(89))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(158, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(144))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(10)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel1)
        			.addGap(24)
        			.addComponent(btnQLHS, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnQLGV, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnQLTK, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnQLTKB, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnDangxuat, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDoimatkhau, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(16))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHSActionPerformed
        // TODO add your handling code here:
        Form_QLHS qlhs = new Form_QLHS();
        qlhs.setVisible(true);
        
    }//GEN-LAST:event_btnQLHSActionPerformed

    private void btnQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGVActionPerformed
        // TODO add your handling code here:
        Form_QLGV qlgv = new Form_QLGV();
        qlgv.setVisible(true);
    }//GEN-LAST:event_btnQLGVActionPerformed

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        // TODO add your handling code here:
        Form_QLTK qltk = new Form_QLTK();
        qltk.setVisible(true);
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnDoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoimatkhauActionPerformed
        // TODO add your handling code here:
        Form_DoimkAD frm = new Form_DoimkAD();
        frm.setVisible(true);
    }//GEN-LAST:event_btnDoimatkhauActionPerformed

    private void btnQLTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKBActionPerformed
        // TODO add your handling code here:
        Form_QLTKB tkb = new Form_QLTKB();
        tkb.setVisible(true);
    }//GEN-LAST:event_btnQLTKBActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnDoimatkhau;
    private javax.swing.JButton btnQLGV;
    private javax.swing.JButton btnQLHS;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnQLTKB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
