/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.UserDAL;
import DTO.UserDTO;
import static GUI.Login.txtPassword;
import static GUI.Login.txtUserName;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Form_DoimkAD extends javax.swing.JFrame {

    /**
     * Creates new form Form_DoimkAD
     */
    public Form_DoimkAD() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNhaplaiMKmoi = new javax.swing.JPasswordField();
        txtMKhientai = new javax.swing.JPasswordField();
        txtMKmoi = new javax.swing.JPasswordField();
        btnDoiMK = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ĐỔI MẬT KHẨU");

        jPanel1.setBackground(new java.awt.Color(252, 218, 183));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mật khẩu hiện tại:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu mới:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nhập lại mật khẩu mới:");

        txtNhaplaiMKmoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMKhientai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMKhientai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKhientaiActionPerformed(evt);
            }
        });

        txtMKmoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMKmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKmoiActionPerformed(evt);
            }
        });

        btnDoiMK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDoiMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addComponent(txtMKhientai)
                    .addComponent(txtNhaplaiMKmoi)
                    .addComponent(txtMKmoi))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMKhientai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNhaplaiMKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoiMK)
                    .addComponent(btnThoat))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMKhientaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKhientaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKhientaiActionPerformed

    private void txtMKmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKmoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKmoiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        // TODO add your handling code here:
        String prePass = "";
        String newPass = "";
        String renewPass = "";
        
        char[] mkhientai = txtMKhientai.getPassword();
        for(int i = 0; i < mkhientai.length; i++) {
                prePass = prePass + mkhientai[i];
        }
        
        char[] mkmoi = txtMKmoi.getPassword();
        for(int j = 0; j < mkmoi.length; j++) {
                newPass = newPass + mkmoi[j];
        }
        char[] nhaplaimkmoi = txtNhaplaiMKmoi.getPassword();
        for(int k = 0; k < nhaplaimkmoi.length; k++) {
                renewPass = renewPass + nhaplaimkmoi[k];
        }
        int rs1 = 0;
        if(prePass.equals("") || newPass.equals("") || renewPass.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin!","Error", JOptionPane.ERROR_MESSAGE);
        }
        else {			       
            if(!GUI.Login.getPass().equals(prePass)) {
                JOptionPane.showMessageDialog(null, "Sai mật khẩu hiện tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else {
                if(newPass.equals(renewPass)) {
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlhs","root","");
                        PreparedStatement ps = conn.prepareStatement("UPDATE user SET password=? WHERE UserName=?");
                        ps.setString(1, newPass);
                        ps.setString(2, GUI.Login.txtUserName.getText());
                        int rs = ps.executeUpdate();
                        if(rs != 0){
                            ps = conn.prepareStatement("UPDATE user SET password=? WHERE username=?");
                            ps.setString(1, newPass);
                            ps.setString(2, GUI.Login.txtUserName.getText());

                            rs1 = ps.executeUpdate();
                            if(rs1 != 0) {
                                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);	
                                setVisible(false);
                            }
                        }

                    } catch (Exception exp) {
                    // TODO: handle exception
                    }
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Mật khẩu mới không trùng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDoiMKActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtMKhientai;
    private javax.swing.JPasswordField txtMKmoi;
    private javax.swing.JPasswordField txtNhaplaiMKmoi;
    // End of variables declaration//GEN-END:variables
}
