/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ThoiKhoaBieuBLL;
import BLL.UserBLL;
import DTO.ThoiKhoaBieuDTO;
import DTO.ThoiKhoaBieuDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author huynh
 */
public class Form_QLTKB extends javax.swing.JFrame {
    /**
     * Creates new form Form_QLTKB
     */
    DefaultTableModel dtm;
    
    List<ThoiKhoaBieuDTO> tkbList = new ArrayList<>();
    public Form_QLTKB() {
    	super("Thời khóa biểu");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        dtm = (DefaultTableModel) tblTKB.getModel();
    }
    
    public void showTKB(){
        String lop = cbLop.getSelectedItem().toString(); 
        List<ThoiKhoaBieuDTO> tkbList = ThoiKhoaBieuBLL.getTkbByLop(lop);
        dtm.setRowCount(0);
        
        tkbList.forEach((tkbDTO) -> {
            dtm.addRow(new Object[] {tkbDTO.getT2(),tkbDTO.getT3(), tkbDTO.getT4(),tkbDTO.getT5(),tkbDTO.getT6()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTKB = new javax.swing.JTable();
        cbT2 = new javax.swing.JComboBox<>();
        cbT3 = new javax.swing.JComboBox<>();
        cbT4 = new javax.swing.JComboBox<>();
        cbT6 = new javax.swing.JComboBox<>();
        cbT5 = new javax.swing.JComboBox<>();
        btnXemTKB = new javax.swing.JButton();
        cbLop = new javax.swing.JComboBox<>();
        btnSuaTKB = new javax.swing.JButton();
        lbLop = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbTiet = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 198));
        jLabel1.setText("QUẢN LÝ THỜI KHÓA BIỂU");
        jLabel1.setAlignmentX(2.0F);

        tblTKB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTKB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6"
            }
        ));
        tblTKB.setRowHeight(30);
        tblTKB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTKBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTKB);

        cbT2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbT2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng việt", "Toán", "Lịch sử & Địa lý", "Âm nhạc", "Mỹ thuật", "Thể dục", "Đạo đức" }));
        cbT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbT2ActionPerformed(evt);
            }
        });

        cbT3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbT3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng việt", "Toán", "Lịch sử & Địa lý", "Âm nhạc", "Mỹ thuật", "Thể dục", "Đạo đức" }));

        cbT4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbT4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng việt", "Toán", "Lịch sử & Địa lý", "Âm nhạc", "Mỹ thuật", "Thể dục", "Đạo đức" }));

        cbT6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbT6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng việt", "Toán", "Lịch sử & Địa lý", "Âm nhạc", "Mỹ thuật", "Thể dục", "Đạo đức" }));

        cbT5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbT5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng việt", "Toán", "Lịch sử & Địa lý", "Âm nhạc", "Mỹ thuật", "Thể dục", "Đạo đức" }));
        cbT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbT5ActionPerformed(evt);
            }
        });

        btnXemTKB.setBackground(new java.awt.Color(0, 153, 0));
        btnXemTKB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnXemTKB.setForeground(new java.awt.Color(255, 255, 255));
        btnXemTKB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconlist.png"))); // NOI18N
        btnXemTKB.setText("XEM");
        btnXemTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTKBActionPerformed(evt);
            }
        });

        cbLop.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "2A", "3A", "4A", "5A" }));

        btnSuaTKB.setBackground(new java.awt.Color(0, 153, 0));
        btnSuaTKB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSuaTKB.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTKB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconedit.png"))); // NOI18N
        btnSuaTKB.setText("SỬA");
        btnSuaTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTKBActionPerformed(evt);
            }
        });

        lbLop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLop.setText("Lớp:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Thứ 2:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Thứ 4:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Thứ 3:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Thứ 5:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Thứ 6:");

        cbTiet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbTiet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tiết :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lbLop)
                        .addGap(18, 18, 18)
                        .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnXemTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbT2, 0, 143, Short.MAX_VALUE)
                    .addComponent(cbT6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbT5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbT4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbT3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTiet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbT4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLop)
                            .addComponent(lbLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXemTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuaTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTKBActionPerformed
        // TODO add your handling code here:
        String Tiet = cbTiet.getSelectedItem().toString();
        String Lop = cbLop.getSelectedItem().toString();
        String T2 = cbT2.getSelectedItem().toString();
        String T3 = cbT3.getSelectedItem().toString();
        String T4 = cbT4.getSelectedItem().toString();
        String T5 = cbT5.getSelectedItem().toString();
        String T6 = cbT6.getSelectedItem().toString();

        ThoiKhoaBieuDTO tkb = new ThoiKhoaBieuDTO(Tiet, Lop, T2, T3, T4, T5, T6);

        ThoiKhoaBieuBLL.update(tkb);
        JOptionPane.showMessageDialog(this, "Sửa thành công");
        showTKB();
    }//GEN-LAST:event_btnSuaTKBActionPerformed

    private void btnXemTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTKBActionPerformed
        // TODO add your handling code here:
        showTKB();
    }//GEN-LAST:event_btnXemTKBActionPerformed

    private void cbT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbT5ActionPerformed

    private void cbT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbT2ActionPerformed

    private void tblTKBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTKBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTKBMouseClicked
      
    
    /**
     * @param args the command line arguments
     */     
        // TODO add your handling code here:
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaTKB;
    private javax.swing.JButton btnXemTKB;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JComboBox<String> cbT2;
    private javax.swing.JComboBox<String> cbT3;
    private javax.swing.JComboBox<String> cbT4;
    private javax.swing.JComboBox<String> cbT5;
    private javax.swing.JComboBox<String> cbT6;
    private javax.swing.JComboBox<String> cbTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLop;
    private javax.swing.JTable tblTKB;
    // End of variables declaration//GEN-END:variables
}
